### ISSUE TITLE
Error while matching file Invalid isoformat string

### ISSUE THREAD

**Issue by jababda** [4c0d3r/namer#18]
File name: Primals Mental Domination - Learning to Accept her True Nature.mp4

Log:
porndb_token: ****************************************
  inplace_name: {site} - {name}.{ext}
  prefer_dir_name_if_available: True
  set_uid: None
  set_gid: None
  write_namer_log: True
  set_dir_permissions: 775
Built on: 2022-03-08T01:13:24Z
  set_file_permissions: 664
Tagging Config:
  enabled_tagging: False
  enabled_poster: True
  enable_metadataapi_genres: False
  default_genre: Adult
  language: eng
Watchdog Config:
  min_file_size: 300mb
  del_other_files: False
  new_relative_path_name: {site}/{name}.{ext}
  watch_dir: data/Namer-Test/watch
  work_dir: data/Namer-Test/work
  failed_dir: data/Namer-Test/failed
  dest_dir: data/Namer-Test/dest
  retry_time: 03:16

2022-03-14 23:19:35 - Start porndb scene watcher.... watching: data/Namer-Test/watch
2022-03-14 23:19:44 - watchdog process called for data/Namer-Test/watch/Primals Mental Domination - Learning to Accept her True Nature.mp4
2022-03-14 23:19:44 - Moving data/Namer-Test/watch/Primals Mental Domination - Learning to Accept her True Nature.mp4 to data/Namer-Test/work/Primals Mental Domination - Learning to Accept her True Nature.mp4 for processing
2022-03-14 23:19:44 - Analyzing: data/Namer-Test/work/Primals Mental Domination - Learning to Accept her True Nature.mp4
2022-03-14 23:19:44 - file: data/Namer-Test/work/Primals Mental Domination - Learning to Accept her True Nature.mp4
2022-03-14 23:19:44 - dir : None
2022-03-14 23:19:44 - Could not parse file name: Primals Mental Domination - Learning to Accept her True Nature.mp4
2022-03-14 23:19:44 - Processing: data/Namer-Test/work/Primals Mental Domination - Learning to Accept her True Nature.mp4
2022-03-14 23:19:44 - Querying: https://api.metadataapi.net/scenes?parse=..Primals.Mental.Domination.-.Learning.to.Accept.her.True.Nature&limit=25
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Querying: https://api.metadataapi.net/scenes?parse=.Primals.Mental.Domination.-.Learning.to.Accept.her.True.Nature&limit=25
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Querying: https://api.metadataapi.net/scenes?parse=.&limit=25
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Querying: https://api.metadataapi.net/scenes?parse=..&limit=25
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Name match was 90.00 for Learning to Accept Her True Nature
2022-03-14 23:19:45 - Error handling data/Namer-Test/watch/Primals Mental Domination - Learning to Accept her True Nature.mp4: 
 Invalid isoformat string: ''
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/namer/watchdog.py", line 138, in on_any_event
    handle(path, self.namer_config)
  File "/usr/local/lib/python3.9/dist-packages/namer/watchdog.py", line 62, in handle
    result = process(to_process, namer_config)
  File "/usr/local/lib/python3.9/dist-packages/namer/namer.py", line 212, in process
    output.search_results = match(output.parsed_file, config.porndb_token)
  File "/usr/local/lib/python3.9/dist-packages/namer/metadataapi.py", line 213, in match
    comparison_results = __metadata_api_lookup(file_name_parts, porndb_token)
  File "/usr/local/lib/python3.9/dist-packages/namer/metadataapi.py", line 60, in __metadata_api_lookup
    name_parts.date =  (date.fromisoformat(name_parts.date)+timedelta(days=-1)).isoformat()
ValueError: Invalid isoformat string: ''
2022-03-15 03:16:00 - Retry failed items:
2022-03-16 03:16:02 - Retry failed items:

I've tried changing up the inplace_name and new_relative_path_name with no success.

**Comment by 4c0d3r** [comment]
Hmmm, yeah, the expected name format should include a date.   "Primals Mental Domination - Learning to Accept her True Nature.mp4"  should be something like   "Primals Mental Domination - 21-02-28 -  Learning to Accept her True Nature.mp4"
or "PrimalsMentalDomination.2021.02.28.Athena.Faris.mp4".   This tool is more about matching when you have a date (with up to a day's worth of slop), and a site, but not necessarily the correct scene name.


This is to ensure the tool never returns false positives and can be left running in an automated process you only occasionally look at.    For command line calls I could see allowing more flexibility.

Regardless I should improve the error messages as such.

**Comment by jababda** [comment]
Can i ask then what the inplace_name config value does? 
Its a little frustrating that I'll need to grab the date for each of the scenes as at that point I'm going to effectively doing the job I wanted namer to do. Though I do understand why for an automated process without a gui you'd want to block false positives. 

Would it perhaps be worth while, when it errors like this it moves it to the error location or a new manual process location with the txt file for possible name suggestions that it did match on? 

That way some of the heavy lifting is done automatically and the names that namer needs are ready to go? 

Totally get it if that change is not within the scope of how you wanted namer to work though :)

**Comment by 4c0d3r** [comment]
Ah,  inplace_name is meant for command line usage where you don't want files moved around.  The file is left in place but renamed using the the "inplace_name" rather than the nested directories likely to be in the other naming configuration used by "watcher".   I can see how my name choice here was poor.

Usually you'll have a file grabbed with site-date-some.mess.of.performers.and.or.scenename-XXX.mp4.   Your use case looks a little odd to me.   I could allow overriding the file name matching regex, but that could get pretty tricky.   Here is the current regex to match file names:   

https://github.com/4c0d3r/namer/blob/main/namer/filenameparser.py#L46-L48

Yeah, it should move to the error location at least, and attempted matches could be tried if I can allow a mechanism to override the parsing of the filename.    Not sure when I can get to this though, I've gotten a bit busy recently.
